version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-sensorama
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sensorama
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sensorama-network
  api:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: api-sensorama
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sensorama
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - sensorama-network

volumes:
  postgres_data:

networks:
  sensorama-network:
    driver: bridge
